version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      timezone: Europe/Berlin
    open-pull-requests-limit: 99
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
